name: Run Laravel Test

on: workflow_dispatch # متى يشتغل: عند push أو PR

jobs:
  laravel-tests: 
    runs-on: ubuntu-latest  # نوع السيرفر

    steps:
    

      - name: print hellow word
        run: echo "hellow  word "

     
