name: 04 Events filters

on:  [push, pull_request]
   

jobs:
  laravel-tests: 
    runs-on: ubuntu-latest  # نوع السيرفر

    steps:
    

      - name: print hellow word
        run: echo "hellow  word "

     
