name: 05 Eventsssssssssss filters

on:
  pull_request:
    types:
      - closed

jobs:
  laravel-tests:
    runs-on: ubuntu-latest  # نوع السيرفر

    steps:
      - name: Print hello world
        run: echo "Hello World"
