name: 05 Eventsfsgggggggggfdtgdgggggggsdgdgdg filters

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest  # نوع السيرفر

    steps:
      - name: Print hello world
        run: echo "Hello World"
